apiVersion: apps/v1
kind: Deployment
metadata: 
  name: java_app_deployment
spec:
  selector:
    matchLabel: 
      app: devops_java_app
  replicas: 3
  template:
    metadata: 
      name: java_app
      label:
        app: devops_java_app
    spec:
      constainers:
      - name: java_app
        image: ravitejadarla5/javapp
        ports: 
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: java_app_service
spec:
  selector:
    app: devops_java_app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer 

  